ThreadPool:ThreadPool.cpp
	g++ -std=c++11  $^ -o $@ -lpthread
con_pro:con_pro.c
	g++ -std=c++11  $^ -o $@ -lpthread
cond:cond.c
	gcc $^ -o $@ -lpthread
mutex:mutex.c
	gcc $^ -o $@ -lpthread
retval:retval.c
	gcc $^ -o $@ -lpthread
create:create.c
	gcc $^ -o $@ -lpthread
